# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be4f144de2c2257ef7424b0e767561542ec2bf972ed93ceebd00a4aa76a219cf66d0eb373915d669f07b9d6f98d072c677de5e6b081b5c3084c3f358c6dd2704

test:
  secret_key_base: 4deb39ef84ab770f3e7538b92f30d9149e58ed2b7d781e9bc361b60f1834756be44b39240bc082fd71abd9c2ddf29c61bf3d7f4d7003f448e2a6b5232ea57efc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
